### PR TITLE
chore(ci): enable workflow Helm test on PRs

### PR DESCRIPTION
**Pull request by fty4**
I'd love if the Helm test workflow is running on PRs.

This would help to verify if a PR breaks the Helm chart.
Currently it is only triggered via manual `workflow_dispatch`.
Other projects in eclipse-tractusx test it the same way.

<hr />

Marco Lecheler [marco.lecheler@mercedes-benz.com](mailto:marco.lecheler@mercedes-benz.com) Mercedes-Benz Tech Innovation GmbH ([ProviderInformation](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md))

### CODE REVIEW

**Comment by fty4** [comment]
current issues:

- [ ] daps test will use wrong endpoint resolving in HTTP 404 and always fail
        (see eclipse-tractusx/daps-helm-chart#38)

- [ ] FailedMount for volumes from script from e.g. job-daps certconsumer

https://github.com/eclipse-tractusx/e2e-testing/blob/6c332561980ba508d2a36c9c84b0958f353c2d99/charts/umbrella/charts/certs/templates/job-daps.yaml#L54-L63

**Review by almadigabor — APPROVED** [review]
Looks good!

**Comment by almadigabor** [comment]
Probably need to include the fixed chart dependencies in this PR for the helm test to pass.

**Comment by fty4** [comment]
> Probably need to include the fixed chart dependencies in this PR for the helm test to pass.

You are right - the mentioned issues above should be the problems. But I think these changes should be in another PR.

**Comment by almadigabor** [comment]
> > Probably need to include the fixed chart dependencies in this PR for the helm test to pass.
> 
> You are right - the mentioned issues above should be the problems. But I think these changes should be in another PR.



> > Probably need to include the fixed chart dependencies in this PR for the helm test to pass.
> 
> You are right - the mentioned issues above should be the problems. But I think these changes should be in another PR.

That is true but until we have the fixes in this branch, the test workflow will fail and PR can't be merged.

**Comment by fty4** [comment]
I just tested it with the changes from #22.
The test was successfully.

Therefore I will wait until this mentioned PR is merged.

<details>
<summary>Helm test</summary>

```bash
 helm test e2e                                                                       
NAME: e2e
LAST DEPLOYED: Wed Jun 21 09:57:44 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE:     e2e-server-test
Last Started:   Wed Jun 21 10:01:56 2023
Last Completed: Wed Jun 21 10:02:00 2023
Phase:          Succeeded
TEST SUITE:     e2e-edcconsumertest-controlplane-readiness
Last Started:   Wed Jun 21 10:01:37 2023
Last Completed: Wed Jun 21 10:01:42 2023
Phase:          Succeeded
TEST SUITE:     e2e-edcconsumertest-dataplane-readiness
Last Started:   Wed Jun 21 10:01:42 2023
Last Completed: Wed Jun 21 10:01:47 2023
Phase:          Succeeded
TEST SUITE:     e2e-edcprovidertest-controlplane-readiness
Last Started:   Wed Jun 21 10:01:47 2023
Last Completed: Wed Jun 21 10:01:52 2023
Phase:          Succeeded
TEST SUITE:     e2e-edcprovidertest-dataplane-readiness
Last Started:   Wed Jun 21 10:01:52 2023
Last Completed: Wed Jun 21 10:01:56 2023
Phase:          Succeeded
```

</details>

**Comment by fty4** [comment]
As assumed - after merging #22 the test will succeed.

**Comment by almadigabor** [comment]
> As assumed - after merging #22 the test will succeed.

Great!:) Can I merge this commit now?

**Comment by fty4** [comment]
yes would be great if this will be merged

**Pull request merged**
