### PR TITLE
feat: Added IRS, Keycloack, sementic hub, registry, discovery charts from the IRS data chain kits

### PR DESCRIPTION
**Pull request by MarkAshraf96**
Updated the helm chart to include:

- Decentral Registry for Provider
- Keycloak
- Edc-vault-agent-injector
- IRS-Frontend
- IRS
- IRS-minio
- IRS-provider-backend
- Discovery

I didn't modify the EDCs that existed in the current repository.
#14

### CODE REVIEW

**Comment by carslen** [comment]
You have to sign the Eclipse Contributor Agreement to contribute to an Eclipse Project repository → https://www.eclipse.org/legal/ECA.php

**Comment by SebastianBezold** [comment]
Hi @MarkAshraf96,

thanks for your contribution! A couple of thoughts though:

Helm already has a [built in approach for subcharts](https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#creating-a-subchart). I see you are creating your own directory to contain subcharts and then use the `file://` reference for dependencies. To properly define subcharts, they should be hosted in the `charts/umbrella/charts` directory. If you place it there, you can use the subchart name in you dependencies instead of `file://`.

But that's just about how subcharts are working in general. In this particular case, I think adding every app as subchart defeats the purpose of the umbrella chart. We want to use it to test if our released apps are working together properly. 
In this case we also want to use the Chart of the single products instead of creating our own Charts for testing. There are two advantages of using the released Charts instead of re-inventing them:

1) We do not have to maintain a separate chart, but can rely on the released Chart for the product
2) In addition to just test the application bundled in a docker image, we are also testing the deployment mechanism released by the product team. We would miss that with separate Charts.

I know that there currently are already subcharts present, but we are actively working on removing them and replace them by just using the released version of the product chart. One reason why it is not done yet is, that there are missing features, that are introduced in the subcharts, but not yet merged in the product repository.

**Review by SebastianBezold — CHANGES_REQUESTED** [review]
I would like you to recosider the subchart approach and favor using the release product charts instead. If subcharts are necessary in specific cases, use the subchart approach provided by helm (`charts` subfolder, reference by name instead of `file://`).

Please also fix the failing checks for ECA, like @carslen mentioned and check the errors on Chart linting

**Comment by MarkAshraf96** [comment]
Hello @SebastianBezold,

Thank You for your fast feedback,
My choice to use the subcharts folder was based on the folder hierarchy used in the [IRS helm chart repo](https://github.com/eclipse-tractusx/item-relationship-service/tree/main/local/deployment/full-irs).
I will work on the modifications and also reach to the IRS team to ask for their point of view on using that hierarchy.

**Review by almadigabor — CHANGES_REQUESTED** [review]
Hey @MarkAshraf96! There is a merge conflict that needs to be resolved, please have a look at that. Also some things I'd like to point out:

- License headers are missing from some of the files. It should be added to every human created/modified, not auto-generated file that will not be overwritten by a tool.
- I would also agree with @SebastianBezold to use the [subcharts approach provided by helm](https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#creating-a-subchart) or by using the actual released product charts available in their repositories or in the [dev helm repository for Eclipse-Tractusx](https://eclipse-tractusx.github.io/charts/dev/index.yaml).
- Also please follow the [guideline on how to be a contributor to the Eclipse Foundation](https://eclipse-tractusx.github.io/docs/oss/getting-started) as the Eclipse check fill fail and your contribution cannot be merged.

**Comment by almadigabor** [comment]
Hi! I would suggest closing this PR and approaching this topic similar to this PR https://github.com/eclipse-tractusx/e2e-testing/pull/38/files#diff-e81867793b2483b6b7569d0e6ff9a70f0fb4b6002e4b69243a42fe5d4351b9f3 instead. The goal would be to add the products to the Chart.yaml as a dependency referencing the official tractus-x helm repository and the charts released there.

**Pull request closed without merging**
